import matplotlib.pyplot as plt
plt.rcParams['font.family']='Times New Roman'
plt.rcParams['font.size']=24
plt.rcParams['lines.linewidth']=2
plt.rcParams['lines.markersize']=2
plt.rcParams['axes.grid']=True
plt.rcParams['axes.labelsize']=28
plt.rcParams['axes.linewidth']=2
plt.rcParams['xtick.labelsize']=24
plt.rcParams['ytick.labelsize']=24
plt.rcParams['axes.grid']=True
plt.rcParams['xtick.direction']='in'
plt.rcParams['ytick.direction']='in'
plt.rcParams['xtick.minor.visible']=True
plt.rcParams['ytick.minor.visible']=True
plt.rcParams['xtick.major.width']=2
plt.rcParams['ytick.major.width']=2
plt.rcParams['xtick.minor.width']=2
plt.rcParams['ytick.minor.width']=2
plt.rcParams['xtick.major.size']=10
plt.rcParams['ytick.major.size']=10
plt.rcParams['xtick.minor.size']=5
plt.rcParams['ytick.minor.size']=5
plt.rcParams['xtick.top']=True
plt.rcParams['ytick.right']=True
plt.rcParams['legend.loc']='upper left'
plt.rcParams['legend.fontsize']=24
